/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Shop API
 * OpenAPI spec version: v1
 */

export interface CustomerDetails {
  firstName?: string | null;
  lastName?: string | null;
  phone?: string | null;
}
