/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Shop API
 * OpenAPI spec version: v1
 */

export interface DeliveryDetails {
  zipCode?: string | null;
  city?: string | null;
  address?: string | null;
}
