/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Shop API
 * OpenAPI spec version: v1
 */

export interface EditProfileCommand {
  name?: string | null;
  currentPassword?: string | null;
  newPassword?: string | null;
  newPasswordConfirm?: string | null;
}
