/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Shop API
 * OpenAPI spec version: v1
 */
import type { GetCategoriesRequest } from "./getCategoriesRequest";

export type GetCategoriesParams = { request?: GetCategoriesRequest };
