/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Shop API
 * OpenAPI spec version: v1
 */

export type GetProductsParams = {
  Name?: string;
  FromPrice?: number;
  ToPrice?: number;
  Page?: number;
  Count?: number;
  OrderBy?: string;
};
