/**
 * Generated by orval v6.10.0 🍺
 * Do not edit manually.
 * Shop API
 * OpenAPI spec version: v1
 */
import type { Product } from './product';

export interface GetProductByIdResponse {
  product?: Product;
}
