/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Shop API
 * OpenAPI spec version: v1
 */
import type { GetProductsRequest } from "./getProductsRequest";

export type GetProductsParams = { request?: GetProductsRequest };
