/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Shop API
 * OpenAPI spec version: v1
 */
import type { SharedCartStatus } from "./sharedCartStatus";
import type { SharedCartItemDto } from "./sharedCartItemDto";

export interface GetSharedCartDetailsResponse {
  cartName?: string | null;
  status?: SharedCartStatus;
  sharedCartItems?: SharedCartItemDto[] | null;
}
