/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Shop API
 * OpenAPI spec version: v1
 */
import type { SharedCartItemDto } from "./sharedCartItemDto";

export interface GetSharedCartItemsResponse {
  cartName?: string | null;
  sharedCartItems?: SharedCartItemDto[] | null;
}
