/**
 * Generated by orval v6.10.0 🍺
 * Do not edit manually.
 * Shop API
 * OpenAPI spec version: v1
 */

export interface LoginUserRequest {
  userName?: string | null;
  password?: string | null;
}
