/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Shop API
 * OpenAPI spec version: v1
 */

export type PaymentMethod = typeof PaymentMethod[keyof typeof PaymentMethod];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentMethod = {
  OnDelivery: "OnDelivery",
  CreditCard: "CreditCard",
} as const;
