/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Shop API
 * OpenAPI spec version: v1
 */
import type { Product } from "./product";

export interface ProductPagedList {
  items?: Product[] | null;
  currentPage?: number;
  totalPages?: number;
  totalItems?: number;
}
