/**
 * Generated by orval v6.10.0 🍺
 * Do not edit manually.
 * Shop API
 * OpenAPI spec version: v1
 */

export interface ProductDto {
  name?: string | null;
  price?: number;
  stock?: number;
  imgUrl?: string | null;
}
