/**
 * Generated by orval v6.10.0 🍺
 * Do not edit manually.
 * Shop API
 * OpenAPI spec version: v1
 */
import type { Category } from "./category";

export interface Product {
  id?: string;
  name?: string | null;
  price?: number;
  stock?: number;
  description?: string | null;
  averageRating?: number;
  imgUrl?: string | null;
  categoryId?: string;
  category?: Category;
}
