/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Shop API
 * OpenAPI spec version: v1
 */

export interface RegisterUserCommand {
  userName?: string | null;
  email?: string | null;
  password?: string | null;
}
