/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Shop API
 * OpenAPI spec version: v1
 */

export interface TopCategory {
  id?: string;
  name?: string | null;
  imgUrl?: string | null;
}
