/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Shop API
 * OpenAPI spec version: v1
 */
import type { SharedCartStatus } from "./sharedCartStatus";

export interface UpdateStatusCommand {
  sharedCartId?: string;
  status?: SharedCartStatus;
}
