/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Shop API
 * OpenAPI spec version: v1
 */
import type { AddItemToCartCommand } from "./addItemToCartCommand";

export interface UpdateCartCommand {
  cartItems?: AddItemToCartCommand[] | null;
}
